# Generated by Django 5.0.1 on 2024-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('customer', 'FEMALE')], max_length=10),
        ),
    ]
