# Generated by Django 4.2.7 on 2024-01-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='dis',
            new_name='amount',
        ),
    ]
