# Generated by Django 4.2.7 on 2024-01-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_dis_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.BooleanField(choices=[('number', 'NUMBER'), ('perecent', 'PERECENT')]),
        ),
    ]
