# Generated by Django 4.2.7 on 2024-01-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discount_discount_code_alter_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('number', 'NUMBER'), ('perecent', 'PERECENT')], max_length=8),
        ),
    ]
