# Generated by Django 4.2.7 on 2024-01-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_category_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory',
            new_name='mojodi',
        ),
    ]
