# Generated by Django 5.0.1 on 2024-01-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_is_active_comment_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mojodi',
            new_name='inventory',
        ),
    ]
