# Generated by Django 5.0.1 on 2024-01-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='dis',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='max_dis',
            new_name='max_amount',
        ),
    ]
