# Generated by Django 4.2.7 on 2024-01-14 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_dis_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('-start',)},
        ),
        migrations.AddField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
