# Generated by Django 4.2.7 on 2024-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_discount_created_at_discount_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
