# Generated by Django 4.2.7 on 2024-01-17 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_discount_discount_code_alter_discount_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 8, 2, 15, 568939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 8, 2, 15, 568939, tzinfo=datetime.timezone.utc)),
        ),
    ]
