# Generated by Django 4.2.7 on 2024-01-21 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_discount_expire_alter_discount_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 2, 39, 347897, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 9, 2, 39, 347897, tzinfo=datetime.timezone.utc)),
        ),
    ]
